on:
  push:
     branches:
       - main

name: renderbook

jobs:
  bookdown:
    name: ubuntu-latest
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Render Book
<<<<<<< HEAD
        run: Rscript setup.R
        # run: Rscript -e 'bookdown::render_book("index.Rmd")'
=======
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
>>>>>>> 62f85bd0aa4de7a505cb09b305d85e5a6c08263f
  
	    - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: commit
        run: |
        git config --global user.email jh2259@mrc-cu.cam.ac.uk
        git config --global user.name xihajun
        git add .
        git commit -m "fig2c generation #8" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
<<<<<<< HEAD
#  checkout-and-deploy:
#   runs-on: ubuntu-latest
#   needs: bookdown
#   steps:
#     - name: Checkout
#       uses: actions/checkout@master
#     - name: Download artifact
#       uses: actions/download-artifact@v1.0.0
#       with:
#         # Artifact name
#         name: _book # optional
#         # Destination path
#         path: _book # optional
#     - name: Deploy to GitHub Pages
#       uses: Cecilapp/GitHub-Pages-deploy@v3
#       env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#          build_dir: docs/ # "_site/" by default
#          email: ${{ secrets.EMAIL }}  # must be a verified email
=======
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          build_dir: _book/ # "_site/" by default
          email: ${{ secrets.EMAIL }}  # must be a verified email
>>>>>>> 62f85bd0aa4de7a505cb09b305d85e5a6c08263f
